### PR TITLE
Translate content into Czech

### PR DESCRIPTION
**Pull request by tursky**
Added the first version of Czech texts: #52

### CODE REVIEW

**Comment by tursky** [comment]
I noticed that my VSCode editor did not work correctly when saving files. There may be problems with Index.cz.md during Prettier formatting. From now I will use Midnight Commander.

**Review by tshemsedinov — APPROVED** [review]
I'll going to land this but don't commit `package-lock` with content changes

**Comment by tshemsedinov** [comment]
Thanks @tursky !
Landed in https://github.com/HowProgrammingWorks/Book/commit/4e3b026460d2d7f4a335aef161adb68d4dc28e1d

**Comment by tursky** [comment]
Of course. I wrote at night, probably missed.

**Pull request closed without merging**
